server:
  port: 8085

#  ssl:
#    key-store-password: changeit
#    key-store: src/main/resources/ebininfosoft-ssl-key.p12
#    key-store-type: PKCS12
#
##SSL Key Info
#security:
#  require-ssl: true

management:
  endpoints:
    enabled-by-default=true:
    jmx:
      exposure:
        include=health,info:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled=true:



logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter=DEBUG: